export {
  LOGIN_MUTATION,
  PERMISSIONS_QUERY,
  REGISTER_MUTATION,
  USERNAME_QUERY
} from './account'
export {
  ADMIN_DIAGRAM_LIST_QUERY,
  ADMIN_DIAGRAM_QUERY,
  ADMIN_NODE_LIST_QUERY,
  ADMIN_NODE_QUERY
} from './admin'
export {
  ADD_CHILD_NODE_MUTATION,
  CREATE_DIAGRAM_MUTATION,
  CREATE_NODE_MUTATION,
  DELETE_DIAGRAM_MUTATION,
  DELETE_NODE_DIAGRAM,
  DIAGRAM_LIST_QUERY,
  DIAGRAM_QUERY,
  NODE_LIST_QUERY,
  NODE_QUERY,
  UPDATE_DIAGRAM_MUTATION,
  UPDATE_NODE_MUTATION
} from './diagram'
